on: 
  schedule: 
    - cron: "0 */48 * * *"
    
  workflow_dispatch:
  
name: air quality

jobs:
  run-r-script:
    permissions: 
        contents: 'write'
        id-token: 'write'
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
      REPO_KEY: ${{secrets.GITHUB_TOKEN}}
      username: github-actions

      
    steps:
      # imports an action from another repository, 
      # that enables the machine
      # to access the code inside our repository
      - uses: actions/checkout@v3 
      # imports an action from another repository, 
      # that installs R on the machine
      - uses: r-lib/actions/setup-r@v2
        with:
          # uses the RStudio Package Manager
          use-public-rspm: true
        
      # imports an action from another repository, 
      # that deals with the dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with: 
          # here we have to add all the packages we used in the script!
          packages: |
            any::httr
            any::jsonlite
            any::data.table
            any::collapse
            any::ggplot2
            any::lubridate
            any::hrbrthemes
          
      - name: Execute Script
        run: |
          Rscript "main.R"           
          
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add data/*
          git commit -am "GH ACTION $(date)"
          git push origin main
        env: 
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
          
      - uses: 'actions/checkout@v4'
    
      - uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCS_WIF }}
          service_account: ${{ secrets.GCS_SA }}
       
      - uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>=363.0.0'
          project_id: poluare-urbana
          
      - name: Commit to gcloud 
        run: |
          gsutil mv -n data/statii/*csv gs://poluare-dataset/statii
          gsutil mv -n data/info/*csv gs://poluare-dataset/info
       
