on: 
  schedule: 
    - cron: "0 */60 * * *"
    
  workflow_dispatch:
  
name: air quality

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
      
    steps:
      # imports an action from another repository, 
      # that enables the machine
      # to access the code inside our repository
      - uses: actions/checkout@v3 
      # imports an action from another repository, 
      # that installs R on the machine
      - uses: r-lib/actions/setup-r@v2
        with:
          # uses the RStudio Package Manager
          use-public-rspm: true
          
      # import actions for google cloud 
      - uses: google-github-actions/setup-gcloud@v0
        with: 
          service_account_email: ${{ secrets.GCS_SA }}
          service_account_key: ${{ secrets.GCS_KEY }}
          project_id: poluare-urbana
          
      # imports an action from another repository, 
      # that deals with the dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with: 
          # here we have to add all the packages we used in the script!
          packages: |
            any::httr
            any::jsonlite
          
      - name: Execute Script
        run: |
          Rscript "main.R"           
      - name: Commit files on google cloud storage
        run: |
          gsutil mv data/*statii* gs://poluare/statii
          gsutil mv data/*info* gs://poluare/info
          rm -r data/*
          
        env: 
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
